image:
  repository: image-registry.openshift-image-registry.svc:5000/0198bb-tools/spilo-15
  tag: "3.0"

fullnameOverride: postgres

persistentVolume:
  size: 1Gi

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

postgresMajorVersion: 15

podSecurityContext:
  runAsNonRoot: true

containerSecurityContext:
  enabled: false

continuousArchive:
  enabled: false
