fullnameOverride: "virus-scan"

clamav:
  resources:
    requests:
      cpu: 50m
      memory: 1.5Gi
    limits:
      cpu: 50m
      memory: 1.5Gi

virusScanService:
  resources:
    limits:
      cpu: 10m
      memory: 50Mi
    requests:
      cpu: 10m
      memory: 50Mi
