fullnameOverride: "virus-scan"

clamav:
  resources:
    requests:
      cpu: 50m
      memory: 1.5Gi
    limits:
      cpu: 100m
      memory: 1.5Gi

virusScanService:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
